import type { Metadata } from "next";
import { Kantumruy_Pro } from "next/font/google";
import "../../globals.css";
import {NavbarComponent} from "@/components/navbar/NavbarComponent";
import React from "react";
import {SidebarComponent} from "@/components/sidebar/SidebarComponent";


const kantumruyPro = Kantumruy_Pro({
    subsets: ["latin"],
    weight: ["400", "700"],
    style: ["normal"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};


export default function RootLayout({  children,  }: Readonly<{ children: React.ReactNode;
}>) {
    return <body
        className={`${kantumruyPro.className} bg-gray-100 grid grid-rows-[auto_1fr] md:grid-cols-12 min-h-screen h-full    `}>
    <aside className="hidden md:block sm:block row-span-2 col-span-2 bg-white shadow-lg">
        <SidebarComponent/>
    </aside>
    <div className="col-span-12 md:col-span-10">
        <NavbarComponent/>
    </div>
    <main className="col-span-12 md:col-span-10 bg-gray-100   overflow-y-auto h-full pt-4 pl-4  hide-scrollbar  rounded-md ">
        {children}
    </main>
    </body>;
}