import type { Metadata } from "next";
import { Kantumruy_Pro } from "next/font/google";
import "../globals.css";
import {NavbarComponent} from "@/components/navbar/NavbarComponent";
import React from "react";
import {SidebarComponent} from "@/components/sidebar/SidebarComponent";


const kantumruyPro = Kantumruy_Pro({
    subsets: ["latin"],
    variable: "--font-kantumruy-pro",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};


export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className={`${kantumruyPro.variable}`}>
        <body className="bg-bg-dashboard">
        {/* Main layout structure */}
        <main className="flex flex-col min-h-screen">
            {/* Navbar at the top (sticky) */}
            <div className="sticky top-0 z-50">
                <NavbarComponent />
            </div>

            {/* Content area with sidebar and children */}
            <div className="flex flex-1 relative">
                {/* Sidebar on the left */}
                <aside className="fixed top-0 left-0 h-screen z-40">
                    <SidebarComponent />
                </aside>

                {/* Main content */}
                <div className="flex-1 p-5 ml-64 rounded-2xl">
                    <div className="w-full h-screen rounded-2xl">
                        {children}
                    </div>
                </div>
            </div>
        </main>
        </body>
        </html>
    );
}